### ISSUE TITLE
General questions on design 2018-12-26

### ISSUE THREAD

**Issue by ghost** [formix/RetroZ#1]
Hi @formix,

First of all: _**great job**_! I like the schematic and the PCB even more. It's great that u use the Z80 SIO IC and that you join the schematics for UART to USB. The way you integrate your RetroZ with possible S80 extension cards is _**very well done and to my opinion flawless**_!

However, I have some minor questions.

# Schematics

### 1. Pull-down resistors

You don't pull down the -BusRq- pin of the CPU. Is there a special reason to keep it floating? I'm attentive to this element, since it's my major mistake on the design of the cpu board of the S80 Version 2.0 :-)

### 2. -Reset-

I'm a bit puzzled on the -Reset- circuit. The switch pulls it down to Gnd when pushed, and the resistor pulls it up by default. However, I don't see what IC1 is doing.

Is there a chance that your button will bounce and disturb the reset process of your RetroZ?

### 3. MEM_EXT

Please ignore my remark on pulling down the MEM_EXT pin in the S80 issue u've opened. You already do so (which I missed at my first reading of your schematics). Sorry for that.

### 4. SIO2_SEL generation

If I'm not mistaking, by using the 74xx138, you reserve all addresses of the format 111001xx (base address 0xE4). Is that correct?

### 5. USB

I'm I correct that you don't implement the UART to USB on your PCB?

# PCB

Is there a reason why u use males for the 2x20 connector on the top side of your PCB? The S80 uses the female side of the connectors on the top side and male connectors on the bottom side.

# Documentation on GitHub

I like your documentation very much. It's clear, extensive, and complete. If you ever feel the urge to document the S80 repository in the same way, please do not hesitate.

# Proposal

If you like, I can put your RetroZ-SBC repository (or a copy of the final version, the files that you choose) as a third party made S80 CPU/SERIAL/MEMORY card in a subdirectory of the S80/hardware. e.g. S80/Hardware/RetroZ-SBC. This can include documentation, libraries, your name and copyright notices, ...

Once you have software for your RetroZ, I can also put versions of your software in the S80/Software directory.

I like to copy in stead of linking, since that way, I prevent having dead links in the future, and I'm sure to have a stable version to distribute to the public.

# On the whole

Splendid job, respect !

**Comment by formix** [comment]
Hi @PaintedBlck , 

First I'd like to thank you for taking some time to review my work, It is really appreciated!

So here are my asnwers:

# A: 1. Pull-down resistors
I totally forgot that one, thanks! But you mean a **pull-up** resistor right? based on the [RC2014 mini schematics](http://rc2014.co.uk/wp-content/uploads/2016/10/RC2014-Mini.pdf), I think both ~BUSREQ and ~BUSACK shall be pulled high. I'll fix that!

# A: 2. Reset
When [IC1](https://www.mouser.ca/ProductDetail/584-ADM803TAKSZ-R7) is powered, it pulls its PIN 2 LOW for 240ms then keep it HIGH. That's it. It is a power-on reset chip that saves a lot of space and some components. On the schematic, it is located left of the processor and it is connected on the bus. I think it would help to have it near the reset button and add some text next to it to make things clearer. 

# A: 3. MEM_EXT
Ok, no issue then :).

# A: 4. SIO2_SEL generation
No, given the way the 74xx138 chip is connected, the reserved addresses are 0x00 to 0x03.

# A: 5. USB
The UART to USB is fully connected and working, based on my previous tests. The FT230XS chip is doing its magic and makes the board plung and play. Note that a USB port marked with a lightning should be used since these ports can deliver more amps (these are charger ports on the computer).

# A: PCB
Yeah, my note under the board's 3D view is wrong, I should have said TOP instead of BOTTOM. I'll fix that.

# A: Documentation on GitHub
Yeah, I'd be pleased to do that. I'll see where I can start and try to fit that in my schedule.

# A: Proposal
That would make sense but I'm still planning to change a few things before I send my board to production. You can do as you wish but I already plan to keep the repos open and images and PDFs where they are since that would break my documentation as well! I'll let you know when I update my things.

Thanks angain for your good words adn comments!
