### ISSUE TITLE
Unable to wake-up the SIO/2 chip

### ISSUE THREAD

**Issue by formix** [formix/RetroZ#3]
Hi all,

I need some help regarding my board. I'm not able to make the SIO/2 chip work. There is a chance that there is some physical issues I guess but I spent 3 months reviewing with some help from other people. For now, I would like to tackle this issues from the software angle.

First to make a quick and dirty 8k ROM, I slapped together Dr Scott M. Baker's ASM files for [SIO initialization](https://github.com/formix/rc2014/blob/master/asm/intsio.asm) and [8k Basic](https://github.com/formix/rc2014/blob/master/basic_work/scbasic/basdisk.asm). I fixed a few labels and changed SIOA_C, SIOA_D, SIOB_C and SIOB_D values to fit with my architecture (0x00, 0x01, 0x02 and 0x03 respectively). See my mashed-up file [here](https://github.com/formix/RetroZ/blob/master/asm/basic/sio_basic_32k.asm).

I expected that to be working but it's not doing anything. To make sure its is not related to my FTDI chip, I removed the SIO/2 chip and connected TX and RX together. The RX and TX leds are flashing with each letter I'm typing and I can see the "echo" in my terminal window.

I spent maybe two hours analyzing the SIO and BASIC asm code but I must admit that I'm still lost. I did slap the two files together within my [ASM source file](https://github.com/formix/RetroZ/blob/master/asm/basic/sio_basic_32k.asm) but it is basically what another shell script from @sbelectronics did (I can't find it anymore though). The `JP $0290` at the end of the first script and the `.ORG $0290` at the beginig of the second comforted me that It was ok like that. Other than a few lost clock cycles, I don't think that the CTC initialization stuff has anything to do with my issue.

I'm working in Ubuntu Bash with zasm.

One strange thing is that the generated ROM file has its instructions and operands inverted. For example, If I create an ASM file containing the following code:

```asm
  .ORG $0000
  LD A, 0
  .END
```
I'm expecting to see `3e00` (3e = `LD A`; 00 => the value `00`) in the resulting ROM file.

But what I see in the hexdump is this:
```hex
0000000 003e                                   
0000002
```
The operand and the instruction are inverted!!! I was expecting to see big-endianess for 16 bits operands but not a flipped instruction! Why are the instruction and operand inverted? Is it an issue? Any idea what might be the overall problem here?

**Comment by ghost** [comment]
To my knowledge, the Z80 is a big-ender, meaning that a 2-byte word (goes for instructions to) inverts its bytes to store them in memory (the same as the Intel 80x86 series do). So your hexdump is correct, since Zasm (and others) make a ROM that is 100% RAM compatible (immediately executable). Just storing things in it won't work.

On the other problem: have you tried to measure the pins of the SIO/2 with a logic analyser (I can advise e.g. the Kingst Logic Analyzer which does the trick for me). That way, you can measure some Z80 pins, some SIO/2 pins and see if the signals that have to arrive at the SIO/2 effectively arrive.

I would also go for the smallest possible program, so to have a good view on the instructions, how they arrive as signals at the SIO/2 and how the SIO/2 reacts on it. e.g. the test programs I've written for the S80 to test the first memory board and the first serial board. e.g. https://github.com/PaintedBlck/S80/blob/master/Software/S80%20Ver%201_0/Serial%20test/S80_serial_test.asm

The smaller the program, the better you can track problems with a logic analyzer. From that small program on, you can extend sendchar to sendstring to printf to ... but you can keep debugging with sendchar by writing out intermediate results.

Grtz,
Filip

**Comment by formix** [comment]
Thanks for your inputs @PaintedBlck! 

You are right, I shall get back to the basics and make things simple. I tried to follow that path at first but I quickly switched to the "slap things together" when I found Dr S.M. Baker's code.

I do not have a logic analyzer, in fact I did not know these things existed at all before you mentionned it. I was crudely debugging using a voltmeter and a barely working analog oscilloscope from the sixties.

About the byte order, I decided lately to unstuck my head from the linux command line and started using the windows MiniPro software to read my BIN files. The hex values there are ordered properly, with the same file than I used to do the hexdump in linux. I don't know what is `hexdump` doing or if I missed a command line switch thing or what. That one was a non issue :).

I'll do what you suggest and update on my progress here.

**Comment by formix** [comment]
I found out! I found out!!!!

The resistor R12 is a pull down.  but for some reason, the reading on it was around 1.9V instead of 0. This line being connected to the OR gate pin 2 to deactivate the RAM and ROM chips if the S80 2M/4M memory expansion board is present (it is also connected on the User port A, PIN 1). 

**That 1.9V value is enough to turn the 74LS32N to HIGH, thus disabling the ROM's ~CE line!!!**

To check if I was right, I jumped that resistor and Bingo, I started to see the TX led flash like crazy and my terminal window being filled with X characters at the tremedeous speed of 115kb!!!!

The fix is to remove that resistor for now and jump it directly with a wire. I will double check but there is a good chance that changing that LS chip for an HCT will do the trick!!!

Man it feels great, that was my first hardware debugging!!!

Big thanks to @PaintedBlck  for you support and wisdom (I ordered a Kingst digital analyzer just yesterday) and to **Sylvain Beauregard**  for his good old oscilloscope!

![20190213_202503](https://user-images.githubusercontent.com/8600014/52756633-05e35b80-2fd0-11e9-9fd2-6cdba2c9f775.jpg)

![20190213_204010](https://user-images.githubusercontent.com/8600014/52756620-f6fca900-2fcf-11e9-80f9-c1ebae08f679.jpg)
